<?php
if(!defined('_GNUBOARD_')) exit; // 개별 페이지 접근 불가

$db_tbl_sql = " CREATE TABLE dain_default (
  de_id INTEGER NOT NULL,
  de_admin_company_owner VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_name VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_saupja_no VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_tel VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_fax VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_tongsin_no VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_zip VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_company_addr VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_info_name VARCHAR(255) NOT NULL DEFAULT '',
  de_admin_info_email VARCHAR(255) NOT NULL DEFAULT '',
  de_shop_skin VARCHAR(255) NOT NULL DEFAULT '',
  de_type1_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_type1_list_mod INTEGER NOT NULL DEFAULT '0',
  de_type1_list_row INTEGER NOT NULL DEFAULT '0',
  de_type1_img_width INTEGER NOT NULL DEFAULT '0',
  de_type1_img_height INTEGER NOT NULL DEFAULT '0',
  de_type2_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_type2_list_mod INTEGER NOT NULL DEFAULT '0',
  de_type2_list_row INTEGER NOT NULL DEFAULT '0',
  de_type2_img_width INTEGER NOT NULL DEFAULT '0',
  de_type2_img_height INTEGER NOT NULL DEFAULT '0',
  de_type3_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_type3_list_mod INTEGER NOT NULL DEFAULT '0',
  de_type3_list_row INTEGER NOT NULL DEFAULT '0',
  de_type3_img_width INTEGER NOT NULL DEFAULT '0',
  de_type3_img_height INTEGER NOT NULL DEFAULT '0',
  de_type4_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_type4_list_mod INTEGER NOT NULL DEFAULT '0',
  de_type4_list_row INTEGER NOT NULL DEFAULT '0',
  de_type4_img_width INTEGER NOT NULL DEFAULT '0',
  de_type4_img_height INTEGER NOT NULL DEFAULT '0',
  de_type5_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_type5_list_mod INTEGER NOT NULL DEFAULT '0',
  de_type5_list_row INTEGER NOT NULL DEFAULT '0',
  de_type5_img_width INTEGER NOT NULL DEFAULT '0',
  de_type5_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_type1_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_type1_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_type1_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_type1_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_type1_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_type2_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_type2_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_type2_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_type2_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_type2_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_type3_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_type3_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_type3_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_type3_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_type3_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_type4_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_type4_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_type4_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_type4_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_type4_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_type5_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_type5_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_type5_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_type5_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_type5_img_height INTEGER NOT NULL DEFAULT '0',
  de_rel_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_rel_list_mod INTEGER NOT NULL DEFAULT '0',
  de_rel_img_width INTEGER NOT NULL DEFAULT '0',
  de_rel_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_rel_list_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_mobile_rel_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_rel_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_rel_img_height INTEGER NOT NULL DEFAULT '0',
  de_search_list_mod INTEGER NOT NULL DEFAULT '0',
  de_search_list_row INTEGER NOT NULL DEFAULT '0',
  de_search_img_width INTEGER NOT NULL DEFAULT '0',
  de_search_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_search_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_search_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_search_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_search_img_height INTEGER NOT NULL DEFAULT '0',
  de_listtype_list_mod INTEGER NOT NULL DEFAULT '0',
  de_listtype_list_row INTEGER NOT NULL DEFAULT '0',
  de_listtype_img_width INTEGER NOT NULL DEFAULT '0',
  de_listtype_img_height INTEGER NOT NULL DEFAULT '0',
  de_mobile_listtype_list_mod INTEGER NOT NULL DEFAULT '0',
  de_mobile_listtype_list_row INTEGER NOT NULL DEFAULT '0',
  de_mobile_listtype_img_width INTEGER NOT NULL DEFAULT '0',
  de_mobile_listtype_img_height INTEGER NOT NULL DEFAULT '0',
  de_bank_use INTEGER NOT NULL DEFAULT '0',
  de_bank_account TEXT NOT NULL,
  de_card_test INTEGER NOT NULL DEFAULT '0',
  de_card_use INTEGER NOT NULL DEFAULT '0',
  de_card_noint_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_card_point INTEGER NOT NULL DEFAULT '0',
  de_settle_min_point INTEGER NOT NULL DEFAULT '0',
  de_settle_max_point INTEGER NOT NULL DEFAULT '0',
  de_settle_point_unit INTEGER NOT NULL DEFAULT '0',
  de_level_sell INTEGER NOT NULL DEFAULT '0',
  de_delivery_company VARCHAR(255) NOT NULL DEFAULT '',
  de_send_cost_case VARCHAR(255) NOT NULL DEFAULT '',
  de_send_cost_limit VARCHAR(255) NOT NULL DEFAULT '',
  de_send_cost_list VARCHAR(255) NOT NULL DEFAULT '',
  de_hope_date_use INTEGER NOT NULL DEFAULT '0',
  de_hope_date_after INTEGER NOT NULL DEFAULT '0',
  de_baesong_content TEXT NOT NULL,
  de_change_content TEXT NOT NULL,
  de_point_days INTEGER NOT NULL DEFAULT '0',
  de_simg_width INTEGER NOT NULL DEFAULT '0',
  de_simg_height INTEGER NOT NULL DEFAULT '0',
  de_mimg_width INTEGER NOT NULL DEFAULT '0',
  de_mimg_height INTEGER NOT NULL DEFAULT '0',
  de_sms_cont1 TEXT NOT NULL,
  de_sms_cont2 TEXT NOT NULL,
  de_sms_cont3 TEXT NOT NULL,
  de_sms_cont4 TEXT NOT NULL,
  de_sms_cont5 TEXT NOT NULL,
  de_sms_use1 BOOLEAN NOT NULL DEFAULT FALSE,
  de_sms_use2 BOOLEAN NOT NULL DEFAULT FALSE,
  de_sms_use3 BOOLEAN NOT NULL DEFAULT FALSE,
  de_sms_use4 BOOLEAN NOT NULL DEFAULT FALSE,
  de_sms_use5 BOOLEAN NOT NULL DEFAULT FALSE,
  de_sms_hp VARCHAR(255) NOT NULL DEFAULT '',
  de_pg_service VARCHAR(255) NOT NULL DEFAULT '',
  de_kcp_mid VARCHAR(255) NOT NULL DEFAULT '',
  de_kcp_site_key VARCHAR(255) NOT NULL DEFAULT '',
  de_inicis_mid VARCHAR(255) NOT NULL DEFAULT '',
  de_inicis_iniapi_key VARCHAR(30) NOT NULL DEFAULT '',
  de_inicis_iniapi_iv VARCHAR(30) NOT NULL DEFAULT '',
  de_inicis_sign_key VARCHAR(255) NOT NULL DEFAULT '',
  de_iche_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_easy_pay_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_easy_pay_services VARCHAR(255) NOT NULL DEFAULT '',
  de_samsung_pay_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_inicis_lpay_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_inicis_kakaopay_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_inicis_cartpoint_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_nicepay_mid VARCHAR(30) NOT NULL DEFAULT '',
  de_nicepay_key VARCHAR(255) NOT NULL DEFAULT '',
  de_item_use_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_item_use_write BOOLEAN NOT NULL DEFAULT FALSE,
  de_cart_keep_term INTEGER NOT NULL DEFAULT '0',
  de_guest_cart_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_admin_buga_no VARCHAR(255) NOT NULL DEFAULT '',
  de_vbank_use VARCHAR(255) NOT NULL DEFAULT '',
  de_taxsave_use BOOLEAN NOT NULL,
  de_taxsave_types TEXT CHECK (\"de_taxsave_types\" IN ('account','vbank','transfer')) NOT NULL DEFAULT 'account',
  de_guest_privacy TEXT NOT NULL,
  de_hp_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_escrow_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_tax_flag_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_kakaopay_mid VARCHAR(255) NOT NULL DEFAULT '',
  de_kakaopay_key VARCHAR(255) NOT NULL DEFAULT '',
  de_kakaopay_enckey VARCHAR(255) NOT NULL DEFAULT '',
  de_kakaopay_hashkey VARCHAR(255) NOT NULL DEFAULT '',
  de_kakaopay_cancelpwd VARCHAR(255) NOT NULL DEFAULT '',
  de_naverpay_mid VARCHAR(255) NOT NULL DEFAULT '',
  de_naverpay_cert_key VARCHAR(255) NOT NULL DEFAULT '',
  de_naverpay_button_key VARCHAR(255) NOT NULL DEFAULT '',
  de_naverpay_test BOOLEAN NOT NULL DEFAULT FALSE,
  de_naverpay_mb_id VARCHAR(255) NOT NULL DEFAULT '',
  de_naverpay_sendcost VARCHAR(255) NOT NULL DEFAULT '',
  de_member_reg_coupon_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_member_reg_coupon_term INTEGER NOT NULL DEFAULT '0',
  de_member_reg_coupon_price INTEGER NOT NULL DEFAULT '0',
  de_member_reg_coupon_minimum INTEGER NOT NULL DEFAULT '0',
  de_toss_use BOOLEAN NOT NULL DEFAULT FALSE,
  de_toss_mid VARCHAR(255) NOT NULL DEFAULT '',
  de_toss_client_key VARCHAR(255) NOT NULL DEFAULT '',
  de_toss_secret_key VARCHAR(255) NOT NULL DEFAULT '',
  de_toss_cancel_pwd VARCHAR(255) NOT NULL DEFAULT ''
); ";

sql_query_pg($db_tbl_sql);
unset($db_tbl_sql);