# 0. PersistentVolumeClaim: 데이터 영속성을 위한 EBS 스토리지
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-admin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
---
# 1. Secret: 데이터베이스 연결 정보
apiVersion: v1
kind: Secret
metadata:
  name: gnuboard-db-secret
type: Opaque
stringData:
  DB_HOST: dpass-mariadb1.cryaauiikrfz.ap-northeast-2.rds.amazonaws.com
  DB_NAME: psd_admin_pass
  DB_USER: psd
  DB_PASSWORD: psd217
---
# 2. ConfigMap: PHP 및 Apache 설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnuboard-config
data:
  php.ini: |
    upload_max_filesize = 100M
    post_max_size = 100M
    max_execution_time = 300
    memory_limit = 512M
    session.gc_maxlifetime = 1440
    session.cookie_httponly = On
    session.use_strict_mode = On
    max_file_uploads = 20
    
  apache.conf: |
    <VirtualHost *:80>
        DocumentRoot /var/www/html
        DirectoryIndex index.php index.html
        
        <Directory /var/www/html>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
        
        # 그누보드 보안 설정
        <Directory /var/www/html/data>
            Options -Indexes
        </Directory>
        
        ErrorLog /var/log/apache2/error.log
        CustomLog /var/log/apache2/access.log combined
    </VirtualHost>
---
# 3. Deployment: 그누보드 애플리케이션
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-admin
  template:
    metadata:
      labels:
        app: php-admin
    spec:
      # 권한 설정만 수행하는 간단한 initContainer
      initContainers:
      - name: setup-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Checking data directory..."
          # data 디렉토리가 이미 데이터를 포함하고 있다면 건드리지 않음
          if [ "$(ls -A /var/www/html/data 2>/dev/null)" ]; then
            echo "Data directory already contains files - preserving them"
            chown -R 33:33 /var/www/html/data
            chmod -R 707 /var/www/html/data
          else
            echo "Data directory is empty - setting up basic structure"
            mkdir -p /var/www/html/data/{cache,session,file,log,member,member_image}
            chown -R 33:33 /var/www/html/data
            chmod -R 707 /var/www/html/data
          fi
          echo "Data setup completed"
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/html
        securityContext:
          runAsUser: 0
      
      containers:
      - name: gnuboard
        image: 289652921928.dkr.ecr.ap-northeast-2.amazonaws.com/dainpass/php-admin-page:latest
        ports:
        - containerPort: 80
        
        # 데이터베이스 연결 환경변수
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gnuboard-db-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gnuboard-db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gnuboard-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gnuboard-db-secret
              key: DB_PASSWORD
        - name: PHP_UPLOAD_MAX_FILESIZE
          value: "100M"
        - name: PHP_POST_MAX_SIZE
          value: "100M"
        - name: PHP_MEMORY_LIMIT
          value: "512M"
          
        # 볼륨 마운트
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/html/data  # data 디렉토리만 PVC에 마운트
        - name: config-volume
          mountPath: /usr/local/etc/php/conf.d/gnuboard.ini
          subPath: php.ini
          
        # 리소스 제한
        resources:
          requests:
            memory: "256Mi"  # 리소스 요구량 줄임
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            
        # 헬스체크 설정 (더 빠르게)
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30  # 빠른 시작
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15  # 더 빠른 준비 상태 확인
          periodSeconds: 10
          timeoutSeconds: 3
          
        # postStart 제거 - Dockerfile에서 모든 설정 완료
        # lifecycle 부분 완전 제거
      
      # 볼륨 설정
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: php-admin-pvc
      - name: config-volume
        configMap:
          name: gnuboard-config
---
# 4. Service: 그누보드 서비스
apiVersion: v1
kind: Service
metadata:
  name: php-admin-service
spec:
  selector:
    app: php-admin
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# 5. Ingress: 외부 접근 설정
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:289652921928:certificate/d0bc9f08-dc65-4d6f-b783-4cd2fe0849db
    alb.ingress.kubernetes.io/group.name: dainpass-services
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true,idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
spec:
  rules:
    - host: k8s.dainpass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: php-admin-service
                port:
                  number: 80